name: Building Debug app

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build_app:
    name: Building app
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android Debug app
        run: ./gradlew assembleDebug

      - name: Build iOS Debug app
        run: xcodebuild -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphoneos build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: androidApp/build/outputs/apk/debug/**.apk
