name: Publishing app to AppStore
on:
  workflow_dispatch:


jobs:
  build_with_signing:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create directory for App Store Connect private keys
        run: mkdir -p ~/.appstoreconnect/private_keys

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.IOS_APP_DISTRIBUTION_CERT_BASE64 }}
          P12_PASSWORD: ${{ secrets.IOS_APP_CERT_PASS }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_APP_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPSTORE_CONNECT_API_KEY_BASE64: ${{ secrets.IOS_APPSTORE_CONNECT_API_KEY_BASE64 }}
          APPSTORE_API_KEY_ID: ${{ secrets.IOS_APPSTORE_API_KEY_ID }}
          APPSTORE_API_KEY_ISSUER_ID: ${{ secrets.IOS_APPSTORE_API_KEY_ISSUER_ID }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          APPSTORE_API_KEY_PATH=~/.appstoreconnect/private_keys/AuthKey_$APPSTORE_API_KEY_ISSUER_ID.p8

          # import certificate, provisioning profile and apikey from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          echo -n "$APPSTORE_CONNECT_API_KEY_BASE64" | base64 --decode -o $APPSTORE_API_KEY_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install iTMSTransporter
        run: |
          wget https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/public/Transporter__OSX/bin/ -O /Applications/Xcode_14.2.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/itms/bin/iTMSTransporter.pkg
          sudo installer -pkg iTMSTransporter.pkg -target /Applications/Xcode_14.2.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/itms/bin/iTMSTransporter
    

      - name: Publish app to AppStore
        run : |
         
         
          xcrun altool --upload-package distribution/FindTravelNow.ipa -t ios \
          --apple-id 6471192930 \
          --bundle-id com.measify.findtravelnow \
          --bundle-short-version-string 1.0.4 \
          --bundle-version 15 \
          --apiKey $APPSTORE_API_KEY_ID \
          --apiIssuer $APPSTORE_API_KEY_ISSUER_ID --verbose
